services:

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  simulator:
    build: ./simulator
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: traffic_user
      POSTGRES_PASSWORD: traffic_pass
      POSTGRES_DB: traffic_db
    ports:
      - "5432:5432"
